apiVersion: v1
kind: Service
metadata:
  name: zookeeper-ip-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '2118'
spec:
  type: NodePort 
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 32300
