apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nifi-ca
  namespace: nifi
  labels:
    app: nifi-ca
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: nifi-ca
  template:
    metadata:
      namespace: nifi
      labels:
        app: nifi-ca
    spec:
      containers:
        - name: nifi-ca
          image: apache/nifi:1.9.2
          ports:
            - containerPort: 8443
              name: ca-client-port
          command:
            - bash
            - -c
            - |
              ../nifi-toolkit-current/bin/tls-toolkit.sh server -c nifi-ca-cs -t <token>
---
# Create service for the nifi-ca replica set
apiVersion: v1
kind: Service
metadata:
  name: nifi-ca-cs
  namespace: nifi
  labels:
    app: nifi-ca
spec:
  type: NodePort
  ports:
    - port: 8443
      name: ca-client-port
      targetPort: 8443
  selector:
    app: nifi-ca
