
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-master-1
  labels:
    type: local
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
