
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-data-0
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
