apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: MY_MINIKUBE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP          
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "$(MY_MINIKUBE_IP):30181"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092" 
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_LISTENERS        
          value: "PLAINTEXT://$(MY_POD_IP):9092"
        image: wurstmeister/kafka
        imagePullPolicy: Always
        name: kafka
        ports:
        - containerPort: 9092
        
