kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch-master-0
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch-master-0
  template:
    metadata:
      labels:
        app: elasticsearch-master-0
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
            
          env:
            - name: PROVISIONER_NAME
              value: example.com/nfs
            - name: NFS_SERVER
              value: 10.0.0.102
            - name: NFS_PATH
              value: /root/srv/nfs/kubedata
           
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.0.102
            path: /root/srv/nfs/kubedata
